# Generated by Django 6.0.4 on 2026-04-23 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchinvite',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='attendance.batch'),
        ),
        migrations.AddField(
            model_name='batchinvite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.batch'),
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_batches', through='attendance.BatchStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchtrainer',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.batch'),
        ),
        migrations.AddField(
            model_name='batchtrainer',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='trainer_batches', through='attendance.BatchTrainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='attendance.institution'),
        ),
        migrations.AddField(
            model_name='session',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.batch'),
        ),
        migrations.AddField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.session'),
        ),
        migrations.AlterUniqueTogether(
            name='batchstudent',
            unique_together={('batch', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='batchtrainer',
            unique_together={('batch', 'trainer')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'student')},
        ),
    ]
